# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RCTRongCloudIMLib' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RCTRongCloudIMLib
  #pod 'yuntongxun-full-sdk', :git => 'ssh://git@github.com/lotosbin/yuntongxun.git', :tag => 'v0.0.1'
  pod 'yuntongxun-full-sdk', :path => '../../yuntongxun'

end
